### ISSUE TITLE
Progression Suggestion

### ISSUE THREAD

**Issue by Garies7** [kwpugh/Gobber_mod_forge#16]
Hi,

More of a "concern" than an issue.. (Sorry didn't see how/where to post suggestions)

So to mine any Gobber ore, you need netherite level pickaxe or a gobber pickaxe.
To get netherite, you need to go to the nether, in the nether you can get nether gobber ores.. so why would you go back to the normal "over world" gobber ore?

I would suggest that you need Diamond level to mine Overworld gobber ore, then netherite to mine nether gobber ore, and then gobber level to mine end gobber.. if this makes sense.. i feel this will make progression "make more sense"..

Thanks for reading
Garies

**Comment by kwpugh** [comment]
I used to use diamond but the progression was far easier.  Since gobber is above netherite, it makes sense that you need netherite tool to mine gobber ore.  Trips to the nether are inconsequential.  You still need to make a gobber pick axe to be able to mine the nether gobber ore.

the progression is: diamond pickaxe -> netherite pickaxe -> gobber pickaxe -> nether gobber pickaxe

**Comment by Garies7** [comment]
Thank you very much for the response.
Sorry about that then, I misunderstood the requirements for nether gobber ore.

But, I still feel its useless then to go to the nether just to go make overworld gobber gear and tools, i would then just make the overworld gobber pick axe, go back to the nether and then mine nether gobber ore to make nether gear and tools. - I understand you need overworld gobber ingots to make nether ingots, but I won't go through the hastle to waste ingots then..

Any possibility to add the option in configs please?

The reason is i'm trying to make a minimilist pack, around 30mods (mainly QOL), and this mod is the only additional gear/armor/tools mod I'm adding, no additional mining etc, so my thinking is that if you spend a bunch of time mining by hand, why waste time in the overworld..

But either way, this is still an awesome mod and going in my pack! Thanks for the mod!!
- bit OP here and there - might make config options a good idea for a lot of pack creators

Cheers
Garies

**Comment by kwpugh** [comment]
Given the removal of "mining level" in recent versions, it is not applicable to change levels via config.

I think the progression is fine.   Players still need to mine iron, gold, and diamond to be able to make some gobber ore.  Keep in mind that make nether gobber ingots require gobber ingots, so the player will need to have a steady supply.

**Comment by kwpugh** [comment]
Since the mining is controlled by tags, I suppose you could try changing via data packs.

if you open the gobber jar file and look into resources/data, there are various tags within the `fabric`, `gobber2`, and `minecraft` folders that control which blocks need which material level and which tools are incorrect for specific levels.

![Screenshot 2024-08-05 at 8 36 34 AM](https://github.com/user-attachments/assets/43ec3031-9ec0-4ac6-a770-71f8d69eb1ad)

**Comment by Garies7** [comment]
Thanks for the response,

Yes I understand you need the one ingot for the next tier ingot.

Thanks for that screenshot of the files, I'll go have a look at that, and see if I can figure that out.

Thanks a bunch!! :)

Cheers
Garies
