### ISSUE TITLE
NeoForge 21.0.42 crash with EarthMobs

### ISSUE THREAD

**Issue by aAndrew3030** [kwpugh/Gobber_mod_forge#8]
Gobber 2.10.3
NeoForge 21.0.42

The game crashes while using Gobber tools

The logs show reference to neoforge change "`21.0.40` Rename ToolActions to ItemAbilities (#1148)"

[debug.log](https://github.com/user-attachments/files/16041712/debug.log)

**Comment by aAndrew3030** [comment]
I tested some more, and it seems to happen when I right click blocks with a gobber tool in my hand

**Comment by kwpugh** [comment]
I checked this out.  I don't believe it is my mod.  I believe it is EarthMob.  It is calling event code that was rename named in 21.0.42.

![Screenshot 2024-06-29 at 5 30 50 PM](https://github.com/kwpugh/gobber_mod_forge/assets/8809210/ff0d2447-3a0a-4e74-bbf6-99665c58145f)

The only reason my paxel was involved is because EarthMobs has an event (the one in the pic) that fires when tools are used.

**Comment by kwpugh** [comment]
it should be `event.getItemAbilities` and ToolActions should be `ItemAbilities`

**Comment by kwpugh** [comment]
According to EarthMobs GitHub, that is built against Neo 21.0.31, which is not going to work on .42 if it uses `ToolActions'.

**Comment by kwpugh** [comment]
This should be an easy fix when EarthMobs updates to 21.042+.

**Comment by kwpugh** [comment]
You can test on your end by right-clicking on a grass block with a vanilla shovel.  Any tool (not just gobber) that uses the `onToolUsing` method will get caught by the EarthMobs event.

**Comment by aAndrew3030** [comment]
I disabled Earth Mobs (until they update it) and all is working again, thanks!

**Comment by kwpugh** [comment]
The EarthMob dev will discover this issue when they update.
